disabled_rules:
 - trailing_whitespace
opt_in_rules:
 - weak_delegate
 - explicit_enum_raw_value
excluded:
  - Carthage/

force_try: warning
force_cast: warning
colon:
  apply_to_dictionaries: false
statement_position:
   statement_mode: uncuddled_else